name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t github-actions-demo .

      - name: Run container
        run: |
          docker run -d -p 8080:5000 --name demo github-actions-demo

      - name: Test application
        run: |
          sleep 3
          curl http://localhost:8080

      - name: Stop container
        if: always()
        run: docker stop demo

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Tag Docker image
      #   run: |
      #     docker tag github-actions-demo ghcr.io/${{ github.repository_owner }}/github-actions-demo:latest

      # - name: Push Docker image
      #   run: |
      #     docker push ghcr.io/${{ github.repository_owner }}/github-actions-demo:latest

      - name: Tag Docker image
        run: |
          docker tag github-actions-demo ghcr.io/shaikvasid/github-actions-demo:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/shaikvasid/github-actions-demo:latest