name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t github-actions-demo .

      - name: Run container
        run: |
          docker run -d -p 8080:5000 --name demo github-actions-demo

      - name: Test application
        run: |
          sleep 3
          curl http://localhost:8080

      - name: Stop container
        if: always()
        run: docker stop demo